### ISSUE TITLE
AndroidRuntimeException when calling startActivity()

### ISSUE THREAD

**Issue by ukasz123** [sidlatau/flutter_email_sender#1]
First line of stacktrace:

> android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.

I suggest doing something like below:
```
val context = registrar.activity() ?: registrar.context()
val flags = if (registrar.activity() !=null) 0 else FLAG_ACTIVITY_NEW_TASK

intent.addFlags(flags)
```

**Comment by sidlatau** [comment]
@ukasz123 thanks for registering an issues! I uploaded v0.0.4 package with suggested fix.

**Comment by ukasz123** [comment]
👌 
Thank you.
