### ISSUE TITLE
Unable to add an attachment from getApplicationDocumentsDirectory()

### ISSUE THREAD

**Issue by keshav1611** [sidlatau/flutter_email_sender#10]
When I add a file in the attachment from getExternalStorageDirectory(), it works fine. But it gives an error or says cannot attach attachment when I use getApplicationDocumentsDirectory() or getTemporaryDirectory(). I get the following error:

`E/MethodChannel#flutter_email_sender(20680): Failed to handle method call
E/MethodChannel#flutter_email_sender(20680): java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.example.clbrapp/app_flutter/Technical_Report.pdf
E/MethodChannel#flutter_email_sender(20680): at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
E/MethodChannel#flutter_email_sender(20680): at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:418)
E/MethodChannel#flutter_email_sender(20680): at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.sendEmail(FlutterEmailSenderPlugin.kt:85)
E/MethodChannel#flutter_email_sender(20680): at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.onMethodCall(FlutterEmailSenderPlugin.kt:30)
E/MethodChannel#flutter_email_sender(20680): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter_email_sender(20680): at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter_email_sender(20680): at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_email_sender(20680): at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_email_sender(20680): at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_email_sender(20680): at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter_email_sender(20680): at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_email_sender(20680): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter_email_sender(20680): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Please solve this, because getExternalStorageDirectory() does not work in IOS.

**Comment by MahMoos** [comment]
I have the same issue here.
I couldn't figure out why its looking in `/data/data/com.example.clbrapp/` while the path I'm providing starts with `/data/user/0/com.example.clbrapp/`

**Comment by vishaldhudum** [comment]
> I couldn't figure out why it's looking in `/data/data/com.example.clbrapp/` while the path I'm providing starts with `/data/user/0/com.example.clbrapp/`

Any updates on this, I have same issue.

**Comment by keshav1611** [comment]
It seems that there is a problem in the **FileProvider class** which being used to get **content:// Uri** from the file.

FlutterEmailSenderPlugin.kt:
```
if (options.hasArgument(ATTACHMENT_PATH)) {
            val attachmentPath = options.argument<String>(ATTACHMENT_PATH)
            if (attachmentPath != null) {
                intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)

                val file = File(attachmentPath)
                val uri = FileProvider.getUriForFile(context, registrar.context().packageName + ".file_provider", file)

                intent.putExtra(Intent.EXTRA_STREAM, uri)
            }
        }
```
 I assume that the path is outside the paths supported by **FileProvider**. I am not sure but I think the problem is here. Any idea how it can be solved?

**Comment by sajadj313** [comment]
I am also facing the same problem. Anyone managed to find a solution?
Thanks

**Comment by atessift** [comment]
My workaround was to copy the file to a temp dir before attaching to the email.

**Comment by sidlatau** [comment]
I have specified an additional `external-files-path` path for file provider, maybe that would help. Check `v2.0.2` plugin version with the fix.

**Comment by keshav1611** [comment]
When I try to run, there is this error in the plugin:

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
e: C:\Flutter files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-2.0.2\android\src\main\kotlin\com\sidlatau\flutteremailsender\FlutterEmailSenderFileProvider.kt: (3, 22): Unresolved reference: content
e: C:\Flutter files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-2.0.2\android\src\main\kotlin\com\sidlatau\flutteremailsender\FlutterEmailSenderFileProvider.kt: (5, 40): Unresolved reference: FileProvider
e: C:\Flutter files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-2.0.2\android\src\main\kotlin\com\sidlatau\flutteremailsender\FlutterEmailSenderPlugin.kt: (4, 22): Unresolved reference: content
e: C:\Flutter files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-2.0.2\android\src\main\kotlin\com\sidlatau\flutteremailsender\FlutterEmailSenderPlugin.kt: (95, 27): Unresolved reference: FileProvider

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_email_sender:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Finished with error: Gradle task assembleDebug failed with exit code 1`

**Comment by sidlatau** [comment]
@keshav1611 - check #13 issue. Your project should be migrated to Android X.

**Comment by skaletaPL** [comment]
I'm using path_provider plugin and it doesn't work with **getApplicationDocumentsDirectory()**. 
I'm ussing version flutter_email_sender: 2.1.0
Exception:
E/MethodChannel#flutter_email_sender(18995): Failed to handle method call
E/MethodChannel#flutter_email_sender(18995): java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/pl.kzpert.kzpert_flutter/app_flutter/Karty zgłoszeniowe PERT/adam-2019-11-02 09-50-34.pdf
E/MethodChannel#flutter_email_sender(18995): 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
E/MethodChannel#flutter_email_sender(18995): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
E/MethodChannel#flutter_email_sender(18995): 	at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.sendEmail(FlutterEmailSenderPlugin.kt:108)
E/MethodChannel#flutter_email_sender(18995): 	at com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.onMethodCall(FlutterEmailSenderPlugin.kt:41)
E/MethodChannel#flutter_email_sender(18995): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_email_sender(18995): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_email_sender(18995): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter_email_sender(18995): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_email_sender(18995): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_email_sender(18995): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_email_sender(18995): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter_email_sender(18995): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_email_sender(18995): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter_email_sender(18995): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

It works with getTemporaryDirectory().

**Comment by lamth140198** [comment]
> I'm using path_provider plugin and it doesn't work with **getApplicationDocumentsDirectory()**.
> I'm ussing version flutter_email_sender: 2.1.0

> It works with getTemporaryDirectory().

@skaletaPL  You save my day. Thanks!

**Comment by psygo** [comment]
Same problem still happening with me on version `2.2.2`. I think I'm going to open another issue, since I can't reopen this one.
