### ISSUE TITLE
For IQOO zen 6 pro, Platform exception occurs.

### ISSUE THREAD

**Issue by engineer-ece** [sidlatau/flutter_email_sender#102]
IQOO zen is been in funtouch os, not able read the file, to send email, please check it.

**Comment by sidlatau** [comment]
There is not enough info here. Do you have a stack trace or a more detailed error message?

**Comment by engineer-ece** [comment]
> There is not enough info here. Do you have a stack trace or a more detailed error message?
it not fetching any issue sir.

**Comment by engineer-ece** [comment]
[+1014 ms] I/flutter (27026): The Dart VM service is listening on ************************************
[+4066 ms] E/FLUTTER_MAILER(27026): size is null or Zero
[  +23 ms] I/flutter (27026): PlatformException(not_available, no email Managers available, null, null)
