### ISSUE TITLE
Question: Max attachement size

### ISSUE THREAD

**Issue by ringonotts** [sidlatau/flutter_email_sender#109]
Hi,

Does anyone know what the max size an attachement can be for Android and iOS please ?

I've got attachments working at a few bytes but a 35MB file doesn't apear as an attachment in the email.

Is there a limitation in this library please ?

TIA, Ringo

**Comment by sidlatau** [comment]
This library doesn't have attachments size limit, vut some email providers have, i.e. Gmail have 25MB size limit https://support.google.com/mail/answer/6584
