### ISSUE TITLE
Build faild on andoid 

### ISSUE THREAD

**Issue by devfadl** [sidlatau/flutter_email_sender#13]
hi there ,
thanks for this plugin 
i have an error after update my android studio and install this plugin .

**`e: /Users/../.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/android/src/main/kotlin/com/sidlatau/flutteremailsender/FlutterEmailSenderFileProvider.kt: (3, 22): Unresolved reference: content
e: /Users/../.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/android/src/main/kotlin/com/sidlatau/flutteremailsender/FlutterEmailSenderFileProvider.kt: (5, 40): Unresolved reference: FileProvider
e: /Users/../.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/android/src/main/kotlin/com/sidlatau/flutteremailsender/FlutterEmailSenderPlugin.kt: (4, 22): Unresolved reference: content
e: /Users/../.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/android/src/main/kotlin/com/sidlatau/flutteremailsender/FlutterEmailSenderPlugin.kt: (85, 27): Unresolved reference: FileProvider

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_email_sender:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Finished with error: Gradle task assembleDebug failed with exit code 1`**

i tried clean ,and install plugin again but error still exist.

thanks

**Comment by sidlatau** [comment]
To use 2.0.0 version your project should be migrated to AndroidX. Refer to this [link ](https://developer.android.com/jetpack/androidx/migrate) for more datails.

**Comment by stefanschaller** [comment]
I hav 

> hi there ,
> thanks for this plugin
> i have an error after update my android studio and install this plugin .
> 
> **`e: /Users/../.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/android/src/main/kotlin/com/sidlatau/flutteremailsender/FlutterEmailSenderFileProvider.kt: (3, 22): Unresolved reference: content
> e: /Users/../.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/android/src/main/kotlin/com/sidlatau/flutteremailsender/FlutterEmailSenderFileProvider.kt: (5, 40): Unresolved reference: FileProvider
> e: /Users/../.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/android/src/main/kotlin/com/sidlatau/flutteremailsender/FlutterEmailSenderPlugin.kt: (4, 22): Unresolved reference: content
> e: /Users/../.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/android/src/main/kotlin/com/sidlatau/flutteremailsender/FlutterEmailSenderPlugin.kt: (85, 27): Unresolved reference: FileProvider
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':flutter_email_sender:compileDebugKotlin'.
> 
> > Compilation error. See log for more details
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 24s
> Finished with error: Gradle task assembleDebug failed with exit code 1`**
> 
> i tried clean ,and install plugin again but error still exist.
> 
> thanks

I got the same error with version 2.0.0
