### ISSUE TITLE
Future doesn't complete

### ISSUE THREAD

**Issue by stefanschaller** [sidlatau/flutter_email_sender#15]
I wanted to know if the sending process is done because I want to show a success Snack-Bar.
But the Future doesn't complete. Do you have any idea?

**Comment by sidlatau** [comment]
Thanks for registering an issue! I released `v2.0.1` with the fix. Future will complete when the email screen will be closed. But keep in mind, that this will not indicate, that email is sent successfully - the user may just cancel email sending.
