### ISSUE TITLE
Release Build Error

### ISSUE THREAD

**Issue by stefanschaller** [sidlatau/flutter_email_sender#16]
I got this error on Android. I would be super happy, if you could help me.

I use AndroidX, The Version 2.0.0 of you package.

The error only occurs in release mode. 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :flutter_email_sender.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 35s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      96,4s
Gradle task assembleRelease failed with exit code 1

**Comment by sidlatau** [comment]
Try to add this:
```
lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
}
```
to `android/app/build.gradle`

Found here: https://github.com/flutter/flutter/issues/22397#issuecomment-428144152
