### ISSUE TITLE
pub.dev still points to 2.0.2

### ISSUE THREAD

**Issue by xni06** [sidlatau/flutter_email_sender#18]
When will you update [pub.dev](https://pub.dev/packages/flutter_email_sender#-versions-tab-) to include 2.0.3?

**Comment by l-k22** [comment]
Using this for time being
```
flutter_email_sender: #^2.0.2
      git: 
        url: https://github.com/sidlatau/flutter_email_sender
```

**Comment by sidlatau** [comment]
Just updated package to `v2.0.3` in [pub.dev](https://pub.dev/packages/flutter_email_sender#-versions-tab-)
