### ISSUE TITLE
Unable to determine switft version

### ISSUE THREAD

**Issue by shinta5150** [sidlatau/flutter_email_sender#19]
flutter_email_sender` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by josephhainline** [comment]
I see this same bug.

**Comment by lclc68lclc** [comment]
I'm getting this bug as well. Is there a workaround?

**Comment by josephhainline** [comment]
@lclc68lclc I believe this is an issue of the flutter project not being created with swift dependencies set up. By default Objective C is used instead. You might trying the answer to this [StackOverflow question](https://stackoverflow.com/questions/54204418/make-flutter-project-swift-compatible-after-creation) although it requires recreating the iOS project which means you lose any tweaks to the project you've made so far. It did solve the problem for me though.
