### ISSUE TITLE
Sending multiple attachments

### ISSUE THREAD

**Issue by irundaia** [sidlatau/flutter_email_sender#2]
Hi!

For my current project I need to send an email with several attachments. I had a quick look at the native api's and I think this is doable for both iOs and Android. 

Would you mind if I created a PR for this? (Assuming I can get it working.)

**Comment by sidlatau** [comment]
Feel free to create PR, I would gladly accept new functionality to this plugin!

**Comment by keshav1611** [comment]
How can I add multiple attachments ?
