### ISSUE TITLE
How to send multiple files ? ( multiple attachments )

### ISSUE THREAD

**Issue by GauravPatni** [sidlatau/flutter_email_sender#23]
is there any way to send multiple files at a time?
As in Email class, "attachmentPath" is a string i.e., not a List <String>?

How to add multiple file path to "attachmentPath" or suggest an alternate way.

Thanks,
Gaurav

**Comment by voivoed** [comment]
Any updates on this? I have a case where I need to email 3 files at the same time... multiple attachments would definitely help. Thanks!

**Comment by RamanujamVaradhan** [comment]
Even I am looking for this use case.

**Comment by sidlatau** [comment]
`v3.0.1` added support to attach multiple files
