### ISSUE TITLE
Unable to build iOS app - Swift version not specified

### ISSUE THREAD

**Issue by bremington** [sidlatau/flutter_email_sender#24]
I added this code to my project, and on first build am getting an error from Xcode

`flutter_email_sender` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Thank you!

**Comment by rockingdice** [comment]
bump this. should check out, cannot build at all

**Comment by rockingdice** [comment]
Solved the issue by the  following link:
https://github.com/pichillilorenzo/flutter_inappbrowser/issues/15#issuecomment-457612853

**Comment by sidlatau** [comment]
Duplicate of #14
