### ISSUE TITLE
Email in Bcc does not work if iOS device has a non English language

### ISSUE THREAD

**Issue by macmatrix** [sidlatau/flutter_email_sender#29]
Hello
If I send an email with bcc and the device is setup with a language other than English, then the email is by default sent to cc rather than bcc

    Email email;
        email = Email(
            body: '',
            subject: '',
            bcc: recipient,
          )
      
this email is sent to cc. I tested with an iOS device in Italian. Any workaround?

**Comment by sidlatau** [comment]
Fixed in v2.2.1
