### ISSUE TITLE
Whatsapp is also shown as option

### ISSUE THREAD

**Issue by boylenssen** [sidlatau/flutter_email_sender#31]
Users select 'whatsapp' in the list, and then it fails. When users taps 'always open with this', they can not easily recover from it.

**Comment by sidlatau** [comment]
I have updated a plugin to choose an email client in Android more accurately when no attachment is used.  Please check version 2.2.0, does it solve your problem?

**Comment by boylenssen** [comment]
I'm sorry, I switched package for this. Will let you know if I switch back. Sure it is fixed now, thanks for your fast response!
