### ISSUE TITLE
Build error on Android

### ISSUE THREAD

**Issue by DCubix** [sidlatau/flutter_email_sender#33]
I have a build error with the latest Flutter version
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/diego/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.2.1/android/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'flutter_email_sender'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /home/diego/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.2.1/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s


The plugin flutter_email_sender could not be built due to the issue above.
```

**Comment by rodrigolmacedo** [comment]
> > Failed to apply plugin [id 'com.android.library']
>    > Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /home/diego/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.2.1/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip

>Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /home/diego/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.2.1/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip


Updated ur gradle?

**Comment by sidlatau** [comment]
I have updated Android dependencies in the package. Please check `v2.2.2` in [pub.dev](https://pub.dev/packages/flutter_email_sender)
