### ISSUE TITLE
Send function on android opens too many share options

### ISSUE THREAD

**Issue by syonip** [sidlatau/flutter_email_sender#40]
Hi,
On Android, invoking the send method shows options to share with WhatsApp, Telegram, Google Drive and many other things in addition to email.
Is there a way to limit the options to just email?

Thanks.

**Comment by UlanNurmatov** [comment]
It's still the issue in version 3.0.1. Did anyone solve it?

**Comment by ttencate** [comment]
Here is how it can be solved, using a second "selector intent": https://stackoverflow.com/questions/4883199/using-android-intent-action-send-for-sending-email/42856167#42856167 I've been using this with great success in another (native Android) app of mine. I'll see if I can send a PR.
