### ISSUE TITLE
Not working on Flutter web

### ISSUE THREAD

**Issue by andreagr** [sidlatau/flutter_email_sender#43]
When calling FlutterEmailSender.send(email) all i get is `MissingPluginException(No implementation found for method send on channel
flutter_email_sender)`

**Comment by britannio** [comment]
It doesn't mention supporting IOS so this is more of a feature request.

Have you tried [url_launcher](https://pub.dev/packages/url_launcher#supported-url-schemes)?

**Comment by camillerimichael** [comment]
I second this. The first time you send, there is no output, the second click outputs as @andreagr mentioned earlier, and the mail is not sent.

**Comment by sidlatau** [comment]
Yes, this plugin is Android/iOS only. Looks like now pub.dev shows correct tags.

**Comment by Muhammad-Ullah** [comment]
@sidlatau did you find a solution? that how to send emails in flutter web?
