### ISSUE TITLE
send mal only in debug device

### ISSUE THREAD

**Issue by mirkoFisi** [sidlatau/flutter_email_sender#46]
Hi and thanks for your work.
I'm new of flutter and app developmant. I'm doing my really first app.
I'm using flutter_email_sender in order to send mails from my app.

I got some problem in the debug phase (with Androind Studio), but I solved changing some parameter in the "smtp_server.dart":

  SmtpServer(this.host,
      {this.port = 465,
      String name,
      this.ignoreBadCertificate = true,
      this.ssl = true,
      this.allowInsecure = true,
      this.username,
      this.password,
      this.xoauth2Token});
}

In particular I had to switch in "this.ignoreBadCertificate = true".

In this way it works if I run the debug with the virtual device on my pc, but when I create the apk and try to use it in my device it doesn' work. No mail is sent.

Do you know I can solve the problem?
Thank you in advance.

**Comment by sidlatau** [comment]
This plugin does not have `SmtpServer` class. maybe this issue is for https://pub.dev/packages/mailer?

**Comment by mirkoFisi** [comment]
> Hi and thanks for your work.
> I'm new of flutter and app developmant. I'm doing my really first app.
> I'm using flutter_email_sender in order to send mails from my app.
> 
> I got some problem in the debug phase (with Androind Studio), but I solved changing some parameter in the "smtp_server.dart":
> 
> SmtpServer(this.host,
> {this.port = 465,
> String name,
> this.ignoreBadCertificate = true,
> this.ssl = true,
> this.allowInsecure = true,
> this.username,
> this.password,
> this.xoauth2Token});
> }
> 
> In particular I had to switch in "this.ignoreBadCertificate = true".
> 
> In this way it works if I run the debug with the virtual device on my pc, but when I create the apk and try to use it in my device it doesn' work. No mail is sent.
> 
> Do you know I can solve the problem?
> Thank you in advance.

Update: 
Solved. It was because of me: I didn't gave the correct right in the AndroidManifest.XML.

Thank you
