### ISSUE TITLE
Unable to determine Swift version

### ISSUE THREAD

**Issue by abodamin** [sidlatau/flutter_email_sender#50]
`
[!] Unable to determine Swift version for the following pods:

- `flutter_email_sender` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod. 
`
this solution might help I guess 
https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value

**Comment by ryanheise** [comment]
@sidlatau It could be helpful to set the swift version directly in the plugin. For an example, see one of the official plugins:

https://github.com/flutter/plugins/blob/master/packages/ios_platform_images/ios/ios_platform_images.podspec

**Comment by sidlatau** [comment]
> @sidlatau It could be helpful to set the swift version directly in the plugin. For an example, see one of the official plugins:
> 
> https://github.com/flutter/plugins/blob/master/packages/ios_platform_images/ios/ios_platform_images.podspec

Thanks for the advice, will do in `v3.1.0` version!
