### ISSUE TITLE
MissingPluginException(No implementation found for method send on channel flutter_email_sender)

### ISSUE THREAD

**Issue by fahadahmed84650** [sidlatau/flutter_email_sender#55]
Hi i facing this issue,
MissingPluginException(No implementation found for method send on channel flutter_email_sender)

i cleaned my project, 
checked pubs, flutter doctor
0 errors,

please help me to solve that error.

**Comment by sidlatau** [comment]
Have you executed flutter run targeting that platform since you changed the pubspec file?
See more info there:
https://github.com/flutter/flutter/issues/10912#issuecomment-310499594
