### ISSUE TITLE
Nullsafety migration

### ISSUE THREAD

**Issue by tneotia** [sidlatau/flutter_email_sender#58]
Hello, it would be great if this library is migrated, especially since Flutter 2.0 is released! Thanks :)

I might be able to migrate since there's a very small amount of code.

**Comment by RR-Reddy** [comment]
@tneotia here is [pull](https://github.com/sidlatau/flutter_email_sender/pull/59) request for null safety migration

**Comment by sidlatau** [comment]
The package is migrated and published! (v5.0.0)
