### ISSUE TITLE
MissingPluginException(No implementation found for method send on channel flutter_email_sender)

### ISSUE THREAD

**Issue by theiskaa** [sidlatau/flutter_email_sender#65]
It's not able to send emails from IOS properly.
In simulator/real-device there must be a setted-as-default email application to not get that error.

**Comment by ahmadjournalpost** [comment]
facing the same issue

**Comment by Mozzus** [comment]
I have the same issue too...

**Comment by rimedar** [comment]
Same here, any solution? Android device v.12

**Comment by sidlatau** [comment]
Please try running `flutter clean` and run the app again. This usually fixes the problem. To info about similar problem:
https://github.com/flutter/flutter/issues/10912

**Comment by rimedar** [comment]
Try re launch the app again, every time that an app use native code, the app need be restarted.
