### ISSUE TITLE
Android: FlutterEmailSender.send future never completes

### ISSUE THREAD

**Issue by zuzi-m** [sidlatau/flutter_email_sender#73]
Hi, I'm using the latest version 5.0.1 of this package with Android and the Future returned by `FlutterEmailSender.send()` never seems to be completed (tested in both emulator as well as real device).

Steps to reproduce:  try to call `await FlutterEmailSender.send()` in an async method and nothing after this call gets executed. If you don't `await` the future everything will continue normally (though the point is to await the result of the future)

Thanks for looking into it. I think I even have a fix for this so if you want I can open a PR with the fix

**Comment by vytautas-pranskunas-** [comment]
Any update on this? Same here....

**Comment by zuzi-m** [comment]
I opened a PR #74 for this
Took me a while to figure out but seems like that fixes it

**Comment by sidlatau** [comment]
v5.0.2 is published with the fix.
