### ISSUE TITLE
Build Failed Xcode

### ISSUE THREAD

**Issue by l-k22** [sidlatau/flutter_email_sender#8]
VSC is unable to build to run on iOS emulator
The following error is returned

```
Launching lib/main.dart on iPhone 8 Plus in debug mode...
Xcode build done.                                           12.5s
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
=== BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/xxxx/SDK/crossplatform/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-1.0.1/ios/Classes/FlutterEmailSenderPlugin.m:2:9: fatal error: 'flutter_email_sender/flutter_email_sender-Swift.h' file not found
#import <flutter_email_sender/flutter_email_sender-Swift.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Could not build the application for the simulator.
```

I made changes to my podfile in order to get OneSignal notifications to work

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by sidlatau** [comment]
Looks like there are some issues with swift plugins in objective-C projects. Can you try do [this](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492)?

**Comment by l-k22** [comment]
Hi, I will try thanks. I'll confirm if this works on Monday.

**Comment by l-k22** [comment]
Making those changes caused failed build in relation to different package now.
Changing to 3.2 throws different errors, 
Swift 3 mode is deprecated, please migrate flutter_email_sender to Swift 4.2
file not found import<flutter_email_sender/flutter_email_sender-Swift.h>

Changing to 4.0 throws the same file not found error.

I'm trying to remember if I created the project with -swift, what is the correct way to do this using Visual Studio Code?

**Comment by l-k22** [comment]
<unknown>:0: error: module map file '/Users/xxx/Documents/Programming/my_app/ios/Pods/Headers/Public/flutter_email_sender/flutter_email_sender.modulemap' not found
<unknown>:0: error: module map file '/Users/xxx/Documents/Programming/my_app/ios/Pods/Headers/Public/flutter_email_sender/flutter_email_sender.modulemap' not found
<unknown>:0: error: missing required module 'SwiftShims'

**Comment by l-k22** [comment]
@sidlatau 
I've been following some other stackoverflow suggestions around this issue, just as I appeared to make progress I ran into another issue. (I'm using flutter_email_sender ^1.1.0)
```
`flutter_email_sender` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the
    `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by baba1472** [comment]
> Looks like there are some issues with swift plugins in objective-C projects. Can you try do [this](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492)?

This did the trick for me.

@l-k22 sounds to me that to fix your next problem, you just need to open the iOS projeect in XCode and assign a Swift version to the main project (and maybe the pod target also).

**Comment by l-k22** [comment]
> > Looks like there are some issues with swift plugins in objective-C projects. Can you try do [this](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492)?
> 
> This did the trick for me.
> 
> @l-k22 sounds to me that to fix your next problem, you just need to open the iOS projeect in XCode and assign a Swift version to the main project (and maybe the pod target also).

Hi, yes I eventually got it working, had to stop using a certain package to send emails but having notifications is more important.

**Comment by OpticNectar** [comment]
Is this project going to be updated to the newest version of Swift? I had the same issue with it notifying me that it won't work with my project cause it uses an old version of Swift.

**Comment by l-k22** [comment]
> > Looks like there are some issues with swift plugins in objective-C projects. Can you try do [this](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492)?
> 
> This did the trick for me.
> 
> @l-k22 sounds to me that to fix your next problem, you just need to open the iOS projeect in XCode and assign a Swift version to the main project (and maybe the pod target also).

I can't use 'use_frameworks!' because OneSignal is set to false.
And 'pod install' fails because the email_sender pod doesn't specify a swift version

**Comment by l-k22** [comment]
I think I'm heading in the right direction following this answer https://stackoverflow.com/a/47530482/469335
I also had to change 'ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES' value in the build settings to '$(inherited)'
Now I have new errors Execution failed for task: flutter_email_sender:compileDebugKotlin

**Comment by gbIxaHue** [comment]
`flutter_email_sender` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

How to fix that?

**Comment by sidlatau** [comment]
As I wrote before this problem appears when Swift plugin is used on Objective-C projects.
Two possible solutions suggested:
1. Convert your project to swift:  
`flutter create -i swift`
That fixed the same problem there: **https://github.com/sidlatau/flutter_email_sender/issues/14#issuecomment-477362833**
2. Or update your project `Podfile`:
```
target 'Runner' do
  use_frameworks! # <--- add this
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0' # <--- add this
    end
  end
end
``` 
That solution is suggested there: https://github.com/flutter/flutter/issues/16049#issuecomment-382629492

I am closing this issue now because both solutions does not require any changes in the plugin code.

**Comment by l-k22** [comment]
I've returned to working on this project. I've tried recreating the project afresh using suggested solution 1 (I can't use solution 2 because the "use_frameworks!" command conflicts with OneSignal Package but I am using Swift version 5).

```
"flutter create --org com.companyname -i swift appname"

** BUILD FAILED **
Xcode's output:
↳
    /Users/xxxxx/Documents/Programming/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/ios/Classes/FlutterEmailSenderPlugin.m:2:9: fatal error:
    'flutter_email_sender/flutter_email_sender-Swift.h' file not found
    #import <flutter_email_sender/flutter_email_sender-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```
So zero progress made, I'm really at a loss here :(

**Comment by sidlatau** [comment]
Looks like rebuilding project with Swift support not always helps. You can try to create Swift project from scratch and copy files manually as proposed there: 

https://github.com/fluttercommunity/flutter_contacts/issues/55#issuecomment-460075045

**Comment by lingster** [comment]
> I've returned to working on this project. I've tried recreating the project afresh using suggested solution 1 (I can't use solution 2 because the "use_frameworks!" command conflicts with OneSignal Package but I am using Swift version 5).
> 
> ```
> "flutter create --org com.companyname -i swift appname"
> 
> ** BUILD FAILED **
> Xcode's output:
> ↳
>     /Users/xxxxx/Documents/Programming/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-2.0.0/ios/Classes/FlutterEmailSenderPlugin.m:2:9: fatal error:
>     'flutter_email_sender/flutter_email_sender-Swift.h' file not found
>     #import <flutter_email_sender/flutter_email_sender-Swift.h>
>             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     1 error generated.
> Could not build the precompiled application for the device.
> Error launching application on My iPhone.
> ```
> 
> ```
> [✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-GB)
>     • Flutter version 1.5.8 at /Users/xxxx/Documents/Programming/flutter
>     • Framework revision 0ba67226ee (7 days ago), 2019-04-24 17:18:28 -0700
>     • Engine revision c63d1cf9c9
>     • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/xxxx/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.6.1
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 33.0.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] VS Code (version 1.33.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.26.1
> 
> [✓] Connected device (2 available)
>     • My iPhone • 00000000-000000000000            • ios • iOS 12.1.4
>     • iPhone Xʀ         • 00000-0000-00000-0000-00000000000 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
> ```
> 
> So zero progress made, I'm really at a loss here :(

have you tried my solution here: 
https://github.com/sidlatau/flutter_email_sender/issues/14#issuecomment-519449773

**Comment by l-k22** [comment]
I gave up. I'm just using url_launcher and passing the mailto:my@email.com as the url, can't send attachments with this method but can do everything else e.g add subject title and body text etc. oh well

**Comment by ricardolopezmobiledev** [comment]
Now it works! I was stuck with this for a couple of hours and the truth is quite simple to fix,

1- in your flutter project go completely delete the "ios" folder
2. Open terminal and within your flutter project folder execute the command "flutter create -i swift."
3. Compile the project normally.

**Comment by lingster** [comment]
Thanks @ricardolopezmobiledev your solution worked for me: 
`rm -rf ios` 
`flutter create -i swift .`

**Comment by shadyshrif** [comment]
This solved my issue, but why this package has that problem?

**Comment by quiet-programmer** [comment]
This did not solve the issue for me... I'm still getting Module 'flutter_email_sender' not found

**Comment by fachrifaul** [comment]
I solved my issue, with some changes like this https://github.com/sidlatau/flutter_email_sender/pull/85/files
Thank you
